-- Keith & Jah recurring household routine
-- This script creates ONLY public.recurring_tasks.
-- It does not alter public.calendar_entries or the game tables.

create table if not exists public.recurring_tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  day_of_week smallint not null check (day_of_week between 1 and 5),
  period text not null default 'daytime' check (period in ('morning','daytime','afternoon','evening','bedtime')),
  event_time time without time zone,
  owner text,
  category text not null default 'other' check (category in ('family','childcare','work','home','activity','other')),
  tags text[] not null default '{}'::text[],
  detail text,
  week_pattern text not null default 'EVERY' check (week_pattern in ('EVERY','A','B')),
  icon_key text,
  active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.recurring_tasks enable row level security;

drop policy if exists "recurring_tasks_read" on public.recurring_tasks;
drop policy if exists "recurring_tasks_insert" on public.recurring_tasks;
drop policy if exists "recurring_tasks_update" on public.recurring_tasks;
drop policy if exists "recurring_tasks_delete" on public.recurring_tasks;

create policy "recurring_tasks_read" on public.recurring_tasks for select to anon using (true);
create policy "recurring_tasks_insert" on public.recurring_tasks for insert to anon with check (true);
create policy "recurring_tasks_update" on public.recurring_tasks for update to anon using (true) with check (true);
create policy "recurring_tasks_delete" on public.recurring_tasks for delete to anon using (true);

grant select, insert, update, delete on public.recurring_tasks to anon;
grant usage, select on all sequences in schema public to anon;

-- Seed the routine that was previously hard-coded into the site.
-- The seed runs only when recurring_tasks is empty.
insert into public.recurring_tasks
  (title, day_of_week, period, owner, category, tags, detail, week_pattern, icon_key, active, sort_order)
select * from (values
  ('Nursery drop-off', 1, 'morning',   'Keith', 'childcare', array['angela','keith','childcare']::text[], 'Keith takes Angela to nursery.', 'EVERY', 'nursery', true, 10),
  ('Office',           1, 'daytime',   'Keith', 'work',      array['keith','work']::text[], 'Keith works from the office.', 'EVERY', 'office', true, 20),
  ('Work away from home',1,'daytime',  'Jah',   'work',      array['jah','work']::text[], 'Jah follows her usual workday.', 'EVERY', 'work', true, 30),
  ('Nursery pickup',   1, 'afternoon', 'Keith', 'childcare', array['angela','keith','childcare']::text[], 'Keith collects Angela from nursery.', 'EVERY', 'pickup', true, 40),
  ('Angela bedtime',   1, 'bedtime',   'Keith', 'family',    array['angela','keith','family']::text[], 'Keith handles Angela''s bedtime routine.', 'EVERY', 'bedtime', true, 50),

  ('Nursery drop-off', 2, 'morning',   'Keith', 'childcare', array['angela','keith','childcare']::text[], 'Keith takes Angela to nursery in Week A.', 'A', 'nursery', true, 10),
  ('Nursery drop-off', 2, 'morning',   'Jah',   'childcare', array['angela','jah','childcare']::text[], 'Jah takes Angela to nursery in Week B.', 'B', 'nursery', true, 10),
  ('Work from home',   2, 'daytime',   'Keith', 'work',      array['keith','work','home']::text[], 'Keith works from home.', 'EVERY', 'home', true, 20),
  ('Work away from home',2,'daytime',  'Jah',   'work',      array['jah','work']::text[], 'Jah works away from home in Week A.', 'A', 'work', true, 30),
  ('Work from home',   2, 'daytime',   'Jah',   'work',      array['jah','work','home']::text[], 'Jah works from home in Week B.', 'B', 'home', true, 30),
  ('Nursery pickup',   2, 'afternoon', 'Jah',   'childcare', array['angela','jah','childcare']::text[], 'Jah collects Angela from nursery.', 'EVERY', 'pickup', true, 40),
  ('Kayaking',         2, 'evening',   'Keith', 'activity',  array['keith','activity']::text[], 'Keith kayaks in the evening.', 'EVERY', 'kayak', true, 50),
  ('Angela bedtime',   2, 'bedtime',   'Jah',   'family',    array['angela','jah','family']::text[], 'Jah handles Angela''s bedtime routine.', 'EVERY', 'bedtime', true, 60),

  ('Yiayia drop-off',  3, 'morning',   'Jah',   'childcare', array['angela','jah','childcare']::text[], 'Jah takes Angela to Yiayia.', 'EVERY', 'yiayia', true, 10),
  ('Office',           3, 'daytime',   'Keith', 'work',      array['keith','work']::text[], 'Keith works from the office.', 'EVERY', 'office', true, 20),
  ('Day off',          3, 'daytime',   'Jah',   'home',      array['jah','home']::text[], 'Jah has her regular day off.', 'EVERY', 'dayoff', true, 30),
  ('Yiayia pickup',    3, 'afternoon', 'Jah',   'childcare', array['angela','jah','childcare']::text[], 'Jah collects Angela from Yiayia.', 'EVERY', 'pickup', true, 40),
  ('Angela bedtime',   3, 'bedtime',   'Keith', 'family',    array['angela','keith','family']::text[], 'Keith handles Angela''s bedtime routine.', 'EVERY', 'bedtime', true, 50),

  ('Nursery drop-off', 4, 'morning',   'Keith', 'childcare', array['angela','keith','childcare']::text[], 'Keith takes Angela to nursery.', 'EVERY', 'nursery', true, 10),
  ('Work from home',   4, 'daytime',   'Keith', 'work',      array['keith','work','home']::text[], 'Keith works from home.', 'EVERY', 'home', true, 20),
  ('Work away from home',4,'daytime',  'Jah',   'work',      array['jah','work']::text[], 'Jah follows her usual workday.', 'EVERY', 'work', true, 30),
  ('Nursery pickup',   4, 'afternoon', 'Jah',   'childcare', array['angela','jah','childcare']::text[], 'Jah collects Angela from nursery.', 'EVERY', 'pickup', true, 40),
  ('Kayaking',         4, 'evening',   'Keith', 'activity',  array['keith','activity']::text[], 'Keith kayaks in the evening.', 'EVERY', 'kayak', true, 50),
  ('Angela bedtime',   4, 'bedtime',   'Jah',   'family',    array['angela','jah','family']::text[], 'Jah handles Angela''s bedtime routine.', 'EVERY', 'bedtime', true, 60),

  ('Nursery drop-off', 5, 'morning',   'Jah',   'childcare', array['angela','jah','childcare']::text[], 'Jah takes Angela to nursery in Week A.', 'A', 'nursery', true, 10),
  ('Nursery drop-off', 5, 'morning',   'Keith', 'childcare', array['angela','keith','childcare']::text[], 'Keith takes Angela to nursery in Week B.', 'B', 'nursery', true, 10),
  ('Office',           5, 'daytime',   'Keith', 'work',      array['keith','work']::text[], 'Keith works from the office.', 'EVERY', 'office', true, 20),
  ('Work from home',   5, 'daytime',   'Jah',   'work',      array['jah','work','home']::text[], 'Jah works from home in Week A.', 'A', 'home', true, 30),
  ('Work away from home',5,'daytime',  'Jah',   'work',      array['jah','work']::text[], 'Jah works away from home in Week B.', 'B', 'work', true, 30),
  ('Julie cleans',     5, 'daytime',   'Julie', 'home',      array['home','julie']::text[], 'Julie comes while Jah is working from home.', 'A', 'clean', true, 40),
  ('Nursery pickup',   5, 'afternoon', 'Jah',   'childcare', array['angela','jah','childcare']::text[], 'Jah collects Angela from nursery.', 'EVERY', 'pickup', true, 50),
  ('Angela bedtime',   5, 'bedtime',   'Keith', 'family',    array['angela','keith','family']::text[], 'Keith handles Angela''s bedtime routine.', 'EVERY', 'bedtime', true, 60)
) as seed(title, day_of_week, period, owner, category, tags, detail, week_pattern, icon_key, active, sort_order)
where not exists (select 1 from public.recurring_tasks limit 1);
